import type { Metadata } from "next";
import NavBar from "@/components/NavBar";
import { ThreeScene } from '../components/ThreeScene';
import "./globals.css";

export const metadata: Metadata = {
  title: "Kevin | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThreeScene />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
